In [1]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[4,5,6],[6,7,8]])
print(np.concatenate([a,b],axis=0))

c=np.array([[1,2,3],[4,5,6]])
d=np.array([[5,6,7],[8,9,10]])
print("\n",np.concatenate([c,d],axis=1))
print("\n",np.concatenate([c,d],axis=0))

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [6 7 8]]

 [[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]]

 [[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]


In [1]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[4,5,6],[6,7,8]])
print(np.stack((a,b),axis=0))
print(np.stack((a,b),axis=1))
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [6 7 8]]]
[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [6 7 8]]]
[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
[[1 2 3]
 [3 4 5]
 [4 5 6]
 [6 7 8]]


In [9]:
a=np.array([np.arange(1,20,3),np.arange(20,40,3),np.arange(40,60,3)])
b=np.array([np.arange(60,80,3),np.arange(80,100,3),np.arange(100,120,3)])

# print(np.stack((a,b),axis=0))
# print(np.stack((a,b),axis=1))
print(np.vstack((a,b)))
print(np.hstack((a,b)))
# print(np.column_stack((a,b)))
# print(np.row_stack((a,b)))
print(np.concatenate([a,b],axis=1))
print(np.concatenate([a,b],axis=0))

[[  1   4   7  10  13  16  19]
 [ 20  23  26  29  32  35  38]
 [ 40  43  46  49  52  55  58]
 [ 60  63  66  69  72  75  78]
 [ 80  83  86  89  92  95  98]
 [100 103 106 109 112 115 118]]
[[  1   4   7  10  13  16  19  60  63  66  69  72  75  78]
 [ 20  23  26  29  32  35  38  80  83  86  89  92  95  98]
 [ 40  43  46  49  52  55  58 100 103 106 109 112 115 118]]
[[  1   4   7  10  13  16  19  60  63  66  69  72  75  78]
 [ 20  23  26  29  32  35  38  80  83  86  89  92  95  98]
 [ 40  43  46  49  52  55  58 100 103 106 109 112 115 118]]
[[  1   4   7  10  13  16  19]
 [ 20  23  26  29  32  35  38]
 [ 40  43  46  49  52  55  58]
 [ 60  63  66  69  72  75  78]
 [ 80  83  86  89  92  95  98]
 [100 103 106 109 112 115 118]]


In [2]:
x=np.arange(16)
print(x.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [36]:
a=list([1,2,3])
a=[i+2 for i in a]
a

[3, 4, 5]

In [39]:
a=np.array([1,2,3])
a+2

array([3, 4, 5])

In [30]:
import math
math.log(10)

2.302585092994046

In [25]:
np.log(10)

2.302585092994046

In [34]:
np.arange(1,10,3)

array([1, 4, 7])

In [48]:
a=[1,2,3]
b=[4,5,6]
sum(a,b)

TypeError: can only concatenate list (not "int") to list

In [46]:
a=np.array([1,2,3])
b=np.array([4,5,6])
sum(a,b)

array([10, 11, 12])

In [47]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [10]:
class Rishav:
    def printname(self):
        print("My name is Rishav Paudel")

In [12]:
a=Rishav().printname()

My name is Rishav Paudel
