In [27]:
a=["m","o","n","t","y","p","y","t","h","o","n"]
print(a)

l=len(a)

print("Length :",l)
print(a[0:11])
print(a[::])
print(a[:5])
print(a[8:])
print(a[0::2])
print(a[:6:2])
print(a[::-1])
print(a[-5:])

['m', 'o', 'n', 't', 'y', 'p', 'y', 't', 'h', 'o', 'n']
Length : 11
['m', 'o', 'n', 't', 'y', 'p', 'y', 't', 'h', 'o', 'n']
['m', 'o', 'n', 't', 'y', 'p', 'y', 't', 'h', 'o', 'n']
['m', 'o', 'n', 't', 'y']
['h', 'o', 'n']
['m', 'n', 'y', 'y', 'h', 'n']
['m', 'n', 'y']
['n', 'o', 'h', 't', 'y', 'p', 'y', 't', 'n', 'o', 'm']
['y', 't', 'h', 'o', 'n']


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[:1])
print(a[0])
print(a[1:])
print(a[1])

[[1 2 3]]
[1 2 3]
[[4 5 6]]
[4 5 6]


In [127]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a))
print(a)
print(a[:1,1:]) 

print(a[:,1:])
print(a[:,:2])

[[1 2 3]
 [4 5 6]]
21
[[1 2 3]
 [4 5 6]]
[[2 3]]
[[2 3]
 [5 6]]
[[1 2]
 [4 5]]


In [130]:
a=np.array([np.arange(1,10,1),np.arange(70,80,1)])
print(np.random.randint(1,20,15))

print(a)
print(np.sum(a[:1]))

c=np.array([np.arange(0,20,2)])
b=np.array([np.arange(20,40,2)])
print(np.sum(c))
print(b,c)
print(np.sum(b))

[18  7  9 11  5  6 15 10  8 17  8  7 11 15 14]
[array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])]
[1 2 3 4 5 6 7 8 9]
90
[[20 22 24 26 28 30 32 34 36 38]] [[ 0  2  4  6  8 10 12 14 16 18]]
290


In [126]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b=np.array([[4,3,2,1],[8,7,6,5],[12,11,10,9],[16,15,14,13]])
print(a,b)
print(np.sum([a,b]))

print(a[2:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
272
[[11 12]
 [15 16]]
