In [70]:
import numpy as np
a=np.arange(10)
b=np.arange(10,20,1)
c=np.array([a,b,a,b])
print(c)
ary=np.split(c,[1,4],axis=0)
print(ary)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), array([], shape=(0, 10), dtype=int32)]
