In [2]:
import numpy as np
a=np.array([1,2,3,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
b=np.array((4,5,6))

In [49]:
print(a)
print(b)

[1 2 3 7 8 9]
[4 5 6]


In [110]:
array=np.arange(100,10,-2)
print(array)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12]


In [125]:
b=np.linspace(5,6,10)
print(b)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [138]:
c=np.full((5,5),1)
print(c,"\n\n")

d=np.full((2,5),5)
print(d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 


[[5 5 5 5 5]
 [5 5 5 5 5]]


In [3]:
import random
a=np.random.random((3,4))
print(a)

[[0.9064499  0.21672406 0.94292514 0.37922272]
 [0.71965961 0.3150566  0.67725039 0.61681928]
 [0.97471276 0.96030098 0.56045696 0.41424211]]


In [9]:
print(np.zeros((3,3)))
print(np.ones((5,5)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [78]:
print(np.random.normal(size=40))

print(np.random.normal())

[ 1.76158302 -1.68617261 -0.75322024 -1.31792964 -0.07955434 -0.47242021
 -0.76232441 -0.49627868 -0.40286032 -1.61052433 -0.71377871  1.80810713
 -0.7433613   0.52635027 -1.4615951  -1.43081955 -0.12500571 -0.15718239
 -0.82957715  0.05520737  1.45473428 -0.90239361  0.0072043   1.0769342
 -1.27340289 -0.32020446  0.5405311  -0.31909739  0.81819973  2.08801865
  0.19079685  0.31712627  0.61413405 -0.57703223 -1.15796464  2.51337939
  2.11245895  0.55496534  0.29319717  1.57831006]
0.8122434782987022


In [79]:
np.random.randint(1,100,100)

array([36, 20, 95, 96, 81, 49,  8, 50, 94, 32, 21, 20, 43, 21, 43, 78, 77,
       59, 83, 82, 51,  2, 84, 55, 14,  2, 61, 11, 47, 36, 47, 59, 98, 38,
       84, 17, 45, 53, 35, 43, 40, 21, 88, 64, 26, 68, 66,  8, 55, 35,  8,
       69, 60, 88, 87, 69, 42, 86, 26, 40, 68, 65, 51, 12, 10,  3, 85, 75,
       88, 95, 56, 71,  2, 56, 65, 62, 66, 63,  4, 60, 66, 57, 11, 29, 97,
       41, 25, 19, 92, 76, 81, 66, 25, 11, 90, 92, 24, 27, 80, 31])

In [116]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("Previous",a.shape)
a.shape=(3,4)
print(a)
print("New",a.shape)


Previous (4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New (3, 4)


In [140]:
a=np.array([[np.arange(40)],[np.arange(20)]])
print(a)
print(a.shape)

[[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])]
 [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])]]
(2, 1)


In [147]:
a=np.arange(10)
a.dtype

dtype('int32')

In [164]:
a=np.arange(10,dtype="int")
print(a)

b=np.arange(20,dtype="float")
print(b)

a=np.full((2,3),1.5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [171]:
a=np.arange(100)
b=a.reshape(2,5,10)
print(b)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [184]:
a=np.linspace(1,5,50)
print(a)
print(a.dtype)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
float64
