In [2]:
import numpy as np
np.__version__

'1.18.1'

In [7]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr=np.repeat(False,16).reshape(4,4)
arr2=np.repeat(1,10).reshape(2,5)
arr

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
arr=np.arange(10).reshape(1,-1)

odd=arr[arr%2==1]
evn=arr[arr%2==0]
print(arr,odd,evn)
print(len(arr))
print(arr.size)
print(arr.shape)

[[0 1 2 3 4 5 6 7 8 9]] [1 3 5 7 9] [0 2 4 6 8]
1
10
(1, 10)


In [40]:
arr=np.arange(10).reshape(1,-1)
arr[arr%2==1]=-1
arr

array([[ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]])

In [57]:
arr=np.arange(10)
arr2=arr.copy()
arr2[arr2%2!=0]=-1
arr,arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]))

In [69]:
arr=np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
arr1=np.arange(1,6)
arr2=np.arange(5,10)
print(np.vstack((arr1,arr2)),"\n")
print(np.hstack((arr1,arr2)))
print(np.concatenate((arr1,arr2)))

[[1 2 3 4 5]
 [5 6 7 8 9]] 

[1 2 3 4 5 5 6 7 8 9]
[1 2 3 4 5 5 6 7 8 9]


In [90]:
a=np.array([1,2,3])
sol=np.hstack((np.repeat(a,3),a,a,a))
sol

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [117]:
# a=np.arange(1,11,1)
# b=np.arange(1,20,2)
# print(a.size,b.size)
# a = np.array([1,2,3,4,5,6,7,8,9,10])
# b = np.array([2,4,6,8,10,12,14,16,18,20])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [119]:
np.unique(a[a==b])

array([2, 4])

In [125]:
# returns all the item present in array A that is not present in B
# and vice versa
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
print(a[~np.isin(a,b)])
print(b[~np.isin(b,a)])

[1 2 3 4]
[6 7 8 9]


In [134]:
a = np.array([1,2,3,2,3,4,1,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int32),)

In [141]:
#listing all the elements between 5 and 10
a = np.array([1,2,3,2,3,4,3,4,5,6,7,2,10,2,7,4,9,4,9,8])
a[(a>5) & (a<10)]

array([6, 7, 7, 9, 9, 8])

In [11]:
# Convert the function maxx that works on two scalars, to work on 
# two arrays.
def maxx(x,y):
    if x>=y:
        return x
    else: 
        return y

def max_pair(a,b):
    a=np.array([max(x,y) for x,y in zip(a,b)])
    return a

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])    
max_pair(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [19]:
a=np.arange(9).reshape(3,3)
print(a)
temp=a[:,1].copy()
temp
a[:,0],a[:,1]=temp,a[:,0]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
a=np.arange(9).reshape(3,3)
print(a)

#reversing rows:
a[::-1,:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [54]:
#reversing columns:
a[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [56]:
np.random.randint(1,100,16).reshape(4,4)

array([[95, 66, 92, 40],
       [ 7, 50, 60, 49],
       [23,  8, 16, 42],
       [ 9, 20, 45, 31]])

In [128]:
np.set_printoptions(precision=3)
b=np.random.randint(1,1000,25).reshape(5,5)
b

array([[813, 930, 942,  71,  12],
       [780, 846, 556, 213, 537],
       [245, 881, 348, 559, 899],
       [ 62,  16, 668, 723, 965],
       [601, 366, 425, 808,  54]])

In [222]:
# np.random.seed(100)
# a=np.random.random([3,3])
# print(a)
# np.set_printoptions(suppress=True)
# a
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=1000, formatter=None)
print("Input")
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

# Desired Output
# > array([[ 0.000543,  0.000278,  0.000425],
# >        [ 0.000845,  0.000005,  0.000122],
# >        [ 0.000671,  0.000826,  0.000137]])

# Solution
print("Solution")
np.set_printoptions(suppress=True)
rand_arr

Input
[[5.43404942e-04 2.78369385e-04 4.24517591e-04]
 [8.44776132e-04 4.71885619e-06 1.21569121e-04]
 [6.70749085e-04 8.25852755e-04 1.36706590e-04]]
Solution


array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])