In [1]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import nltk
import re

In [2]:
noise_list=['is','a','this','...']
def remove_noise(input_text):
    words=input_text.split()
    noise_free=[word for word in words if word not in noise_list]
    noise_free=' '.join(noise_free)
    
    
    
    return noise_free

remove_noise("this is a sample text")

'sample text'

In [3]:
def remove_noise(input_text):
    pattern="#[\w]*"
    urls=re.finditer(pattern,input_text)
    for i in urls:
        input_text=re.sub(i.group().strip(),'',input_text)
    return input_text

remove_noise("remove this #hashtag from analytics vidhya")

'remove this  from analytics vidhya'

In [4]:
def remove_noise(input_text):
    pattern="[^a-zA-Z]"
    input_text=re.sub(pattern,' ',input_text)
    
        
    return input_text

remove_noise("remove this #hashtag from analytics vidhya")

'remove this  hashtag from analytics vidhya'

In [5]:
lem=WordNetLemmatizer()
stmr=PorterStemmer()

In [6]:
lem.lemmatize('Playing')

'Playing'

In [7]:
stmr.stem('Playing')

'play'

In [8]:
lem.lemmatize("multiplying",'v')

'multiply'

In [9]:
lem.lemmatize("Sleeps",'v')

'Sleeps'

In [10]:
stmr.stem('multiply')

'multipli'

In [11]:
lookup_dict = {'rt':'Retweet', 'dm':'direct message', "awsm" : "awesome", "luv" :"love"}

In [12]:
lookup_dict

{'rt': 'Retweet', 'dm': 'direct message', 'awsm': 'awesome', 'luv': 'love'}

In [13]:
def lookup_word(input_text):
    words=input_text.split()
    new_words=[]
    for word in words:
        if word.lower() in lookup_dict:
            temp_word=lookup_dict[word.lower()]
            new_words.append(temp_word)
        else:
            new_words.append(word)
    return ' '.join(new_words)
    
    
lookup_word("RT this is a retweeted tweet by Shivam Bansal")

'Retweet this is a retweeted tweet by Shivam Bansal'

In [14]:
from nltk import word_tokenize,pos_tag

In [15]:
text = "I am learning Natural Language Processing on Jupyter Notebook"
tokens=word_tokenize(text)

In [16]:
print(tokens)

['I', 'am', 'learning', 'Natural', 'Language', 'Processing', 'on', 'Jupyter', 'Notebook']


In [17]:
print(pos_tag(tokens))

[('I', 'PRP'), ('am', 'VBP'), ('learning', 'VBG'), ('Natural', 'NNP'), ('Language', 'NNP'), ('Processing', 'NNP'), ('on', 'IN'), ('Jupyter', 'NNP'), ('Notebook', 'NNP')]


In [18]:
sent="book my flight, I will read this book"
print(pos_tag(sent.split()))

[('book', 'NN'), ('my', 'PRP$'), ('flight,', 'NN'), ('I', 'PRP'), ('will', 'MD'), ('read', 'VB'), ('this', 'DT'), ('book', 'NN')]


In [19]:
doc1 = "Sugar is bad to consume. My sister likes to have sugar, but not my father." 
doc2 = "My father spends a lot of time driving my sister around to dance practice."
doc3 = "Doctors suggest that driving may cause increased stress and blood pressure."
doc_complete = [doc1, doc2, doc3]
doc_clean = [doc.split() for doc in doc_complete]

In [20]:
def generate_ngrams(text,n):
    words=text.split()
    bigrams=[]
    for i in range(len(words)-n+1):
#         bigrams.append([words[i],words[i+1]])
        bigrams.append(words[i:i+n])
        
    return bigrams
generate_ngrams("this is a sample text",2)

[['this', 'is'], ['is', 'a'], ['a', 'sample'], ['sample', 'text']]

In [21]:
generate_ngrams("this is a sample text",3)

[['this', 'is', 'a'], ['is', 'a', 'sample'], ['a', 'sample', 'text']]

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [23]:
vec=TfidfVectorizer()
corpus=['This is sample document.', 'another random document.', 'third sample document text']
X=vec.fit_transform(corpus)

In [24]:
X

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [25]:
X.toarray()

array([[0.        , 0.34520502, 0.5844829 , 0.        , 0.44451431,
        0.        , 0.        , 0.5844829 ],
       [0.65249088, 0.38537163, 0.        , 0.65249088, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.34520502, 0.        , 0.        , 0.44451431,
        0.5844829 , 0.5844829 , 0.        ]])

In [26]:
from gensim.models import Word2Vec
sentences = [['data', 'science'], ['vidhya', 'science', 'data', 'analytics'],['machine', 'learning'], ['deep', 'learning']]

In [27]:
model=Word2Vec(sentences,min_count=1)

In [28]:
model.similarity('machine','learning')

C:\Users\rissu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `similarity` (Method will be removed in 4.0.0, use self.wv.similarity() instead).
  """Entry point for launching an IPython kernel.


0.2216787

In [29]:
model.similarity('data','analytics')

C:\Users\rissu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `similarity` (Method will be removed in 4.0.0, use self.wv.similarity() instead).
  """Entry point for launching an IPython kernel.


-0.01849537

In [30]:
model['learning']

C:\Users\rissu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-1.6076090e-03, -1.3852287e-03, -2.0308003e-03, -4.6457499e-04,
       -4.6547242e-03, -5.4621260e-04, -3.9414368e-03, -1.3360038e-03,
       -2.2766725e-03, -2.9404771e-03, -2.6110695e-03, -4.5441105e-03,
        1.8632767e-03,  1.6227149e-03, -3.1435799e-03,  3.0260280e-04,
       -1.0196615e-03, -4.2854459e-03, -3.1398393e-03, -4.6504373e-03,
        9.9747698e-04,  2.4565668e-03, -2.8441364e-03,  5.6081056e-04,
       -3.5144761e-03,  2.9678976e-03, -3.2669640e-04, -1.7613007e-03,
        2.6149256e-03,  4.3443241e-03, -4.7916588e-03, -2.6434376e-03,
        3.9560180e-03,  2.0129057e-03,  4.2406917e-03,  2.7763569e-03,
        1.2021171e-03,  1.7931158e-04, -1.2499637e-03, -2.0527255e-05,
        1.8216885e-03, -4.2563723e-03, -1.7569074e-03,  2.5828031e-03,
        5.4135843e-04, -3.2301564e-03,  3.9379830e-03,  4.6115960e-03,
       -3.6772143e-03, -4.8010545e-03,  2.8808261e-05, -4.9538550e-04,
        1.8307751e-03,  1.2372570e-03,  2.6552421e-03,  8.7721513e-05,
      

In [31]:
from textblob.classifiers import NaiveBayesClassifier as NBC
from textblob import TextBlob
training_corpus = [
                   ('I am exhausted of this work.', 'Class_B'),
                   ("I can't cooperate with this", 'Class_B'),
                   ('He is my badest enemy!', 'Class_B'),
                   ('My management is poor.', 'Class_B'),
                   ('I love this burger.', 'Class_A'),
                   ('This is an brilliant place!', 'Class_A'),
                   ('I feel very good about these dates.', 'Class_A'),
                   ('This is my best work.', 'Class_A'),
                   ("What an awesome view", 'Class_A'),
                   ('I do not like this dish', 'Class_B')]
test_corpus = [
                ("I am not feeling well today.", 'Class_B'), 
                ("I feel brilliant!", 'Class_A'), 
                ('Gary is a friend of mine.', 'Class_A'), 
                ("I can't believe I'm doing this.", 'Class_B'), 
                ('The date was good.', 'Class_A'), ('I do not enjoy my job', 'Class_B')]

In [32]:
model=NBC(training_corpus)

In [33]:
for i in test_corpus:
    word=i[0]
    print(model.classify(word))

Class_B
Class_A
Class_B
Class_B
Class_A
Class_B


In [34]:
model.classify('I dont like their service')

'Class_B'

In [35]:
model.accuracy(test_corpus)

0.8333333333333334

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
from sklearn import svm

In [37]:
train_data=[]
train_labels=[]
test_data=[]
test_labels=[]


In [38]:
for row in training_corpus:
    train_data.append(row[0])
    train_labels.append(row[1])
for row in test_corpus:
    test_data.append(row[0])
    test_labels.append(row[1])

In [39]:
vectorizer=TfidfVectorizer(min_df=4,max_df=0.9)
train_vectors=vectorizer.fit_transform(train_data)
test_vectors=vectorizer.transform(test_data)

In [40]:
model=svm.SVC(kernel='linear')

In [41]:
model.fit(train_vectors,train_labels)

SVC(kernel='linear')

In [42]:
predictions=model.predict(test_vectors)
predictions

array(['Class_A', 'Class_A', 'Class_B', 'Class_B', 'Class_A', 'Class_A'],
      dtype='<U7')

In [43]:
print(classification_report(test_labels,predictions))

              precision    recall  f1-score   support

     Class_A       0.50      0.67      0.57         3
     Class_B       0.50      0.33      0.40         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6



In [44]:
train_vectors.toarray()

array([[0.        , 1.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.77635539, 0.63029542],
       [0.        , 0.        ],
       [0.77635539, 0.63029542],
       [0.        , 0.        ],
       [0.        , 1.        ]])

In [45]:
def levenshtein(s1,s2):
    if len(s1)>len(s2):
        s1,s2=s2,s1
    distances=range(len(s1)+1)
    print(distances)
    for index2,char2 in enumerate(s2):
        newDistances=[index2+1]
        for index1,char1 in enumerate(s1):
            if char1==char2:
                newDistances.append(distances[index1])
            else:
                newDistances.append(1 + min((distances[index1], distances[index1+1], newDistances[-1]))) 
        distances=newDistances
    print(distances,distances[-1])
        
        
levenshtein("analyze","anaalallyze")

range(0, 8)
[11, 10, 9, 8, 7, 6, 5, 4] 4


In [46]:
import math
from collections import Counter

In [47]:
def get_cosine(vec1,vec2):
    common=set(vec1.keys()) & set(vec2.keys())
    numerator=sum(vec1[x]*vec2[x] for x in common)

    sum1=sum([vec1[x]**2 for x in vec1.keys()])
    sum2=sum([vec2[x]**2 for x in vec2.keys()])
    denominator=math.sqrt(sum1)*math.sqrt(sum2)
    
    if not denominator:
        return 0.0
    else:
        return numerator/denominator
    
def text_to_vector(text): 
    words = text.split() 
    return Counter(words)


text1 = 'This is an article on analytics vidhya' 
text2 = 'T'

vect1 = text_to_vector(text1) 
vect2 = text_to_vector(text2)    
get_cosine(vect1,vect2)

0.0