In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
onehot_rep=[one_hot(word,voc_size) for word in sent]

In [6]:
onehot_rep

[[3401, 6031, 6582, 4291],
 [3401, 6031, 6582, 9524],
 [3401, 4917, 6582, 997],
 [7061, 766, 3271, 7537, 1847],
 [7061, 766, 3271, 7537, 1601],
 [6617, 3401, 1269, 6582, 6345],
 [4552, 7845, 5775, 7537]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [11]:
sent_len=8
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0, 3401, 6031, 6582, 4291],
       [   0,    0,    0,    0, 3401, 6031, 6582, 9524],
       [   0,    0,    0,    0, 3401, 4917, 6582,  997],
       [   0,    0,    0, 7061,  766, 3271, 7537, 1847],
       [   0,    0,    0, 7061,  766, 3271, 7537, 1601],
       [   0,    0,    0, 6617, 3401, 1269, 6582, 6345],
       [   0,    0,    0,    0, 4552, 7845, 5775, 7537]])

In [12]:
dim=15

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_len))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.predict(embedded_docs)[0]

array([[ 0.04059331,  0.0139527 , -0.01600055,  0.03386256,  0.00159238,
         0.03086097, -0.02182965, -0.04902672,  0.02390294,  0.03917695],
       [ 0.04059331,  0.0139527 , -0.01600055,  0.03386256,  0.00159238,
         0.03086097, -0.02182965, -0.04902672,  0.02390294,  0.03917695],
       [ 0.04059331,  0.0139527 , -0.01600055,  0.03386256,  0.00159238,
         0.03086097, -0.02182965, -0.04902672,  0.02390294,  0.03917695],
       [ 0.04059331,  0.0139527 , -0.01600055,  0.03386256,  0.00159238,
         0.03086097, -0.02182965, -0.04902672,  0.02390294,  0.03917695],
       [-0.021208  ,  0.03164264,  0.02176757,  0.03374905,  0.03698038,
         0.0422279 ,  0.03087649,  0.00380771,  0.00852204,  0.02350787],
       [-0.00227009,  0.01187164, -0.00523112, -0.01465929, -0.02828833,
        -0.02428681,  0.02798544,  0.04019072,  0.01914367, -0.01687495],
       [ 0.03522054, -0.03560526, -0.04491654,  0.02917457,  0.04917235,
        -0.01651084, -0.02781159, -0.02626278

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3401, 6031, 6582, 4291])