In [31]:
import numpy as np
import pandas as pd
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
 index=['Ohio', 'Colorado', 'Utah', 'New York'],
 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
data.drop(['Ohio'],inplace=True)

In [15]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [18]:
data.drop(['one','two'],axis=1)

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [19]:
data.drop(['Ohio'],axis=0)

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [29]:
data=data[['one','four']]
data

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [38]:
data.loc['Ohio':'Utah']

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [43]:
ser=pd.Series(np.random.randint(1,10,10))
ser

0    2
1    8
2    4
3    1
4    2
5    3
6    9
7    4
8    8
9    1
dtype: int32

In [44]:
ser[:5]

0    2
1    8
2    4
3    1
4    2
dtype: int32

In [53]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
    index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1,df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [48]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [50]:
pd.concat([df1,df2])

b    c     d     e
Ohio      0.0  1.0   2.0   NaN
Texas     3.0  4.0   5.0   NaN
Colorado  6.0  7.0   8.0   NaN
Utah      0.0  NaN   1.0   2.0
Ohio      3.0  NaN   4.0   5.0
Texas     6.0  NaN   7.0   8.0
Oregon    9.0  NaN  10.0  11.0

In [56]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [61]:
a=['asd','asdsa','asdasd','refv']


NameError: name 'strip' is not defined

In [66]:
a=pd.Series(np.random.randint(1,10,10))

In [67]:
print(a)
a.rank()

0    4
1    7
2    9
3    4
4    6
5    2
6    9
7    4
8    3
9    7
dtype: int32


0    4.0
1    7.5
2    9.5
3    4.0
4    6.0
5    1.0
6    9.5
7    4.0
8    2.0
9    7.5
dtype: float64

In [71]:
a=pd.Series(np.random.rand(10))
a

0    0.640765
1    0.996749
2    0.025063
3    0.380545
4    0.843587
5    0.202929
6    0.208453
7    0.568028
8    0.132780
9    0.807359
dtype: float64

In [72]:
a.rank()

0     7.0
1    10.0
2     1.0
3     5.0
4     9.0
5     3.0
6     4.0
7     6.0
8     2.0
9     8.0
dtype: float64

In [76]:
df2,df2.cumsum()

(          b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0,
            b     d     e
 Utah     0.0   1.0   2.0
 Ohio     3.0   5.0   7.0
 Texas    9.0  12.0  15.0
 Oregon  18.0  22.0  26.0)

In [84]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,10)


In [87]:
a,b,np.corrcoef(a,b)

(array([4, 1, 8, 9, 4, 3, 3, 5, 8, 4]),
 array([8, 6, 3, 8, 2, 9, 6, 5, 9, 1]),
 array([[1.       , 0.1277963],
        [0.1277963, 1.       ]]))