In [219]:
import numpy as np
import pandas as pd
from numpy import nan as NA

In [220]:
a={"A":"Apple",
                "B":"Ball",
                "C":"Cat",
                "D":"Dog",
                "E":"Elephant",
                "F":"Fan",
                "G":"Glass"}

df=pd.DataFrame({'Letters':[chr(i) for i in range(65,72)],
                 'Words':['Ant','Butter','Chocolate','Donkey',NA,NA,NA]})

In [221]:
a

{'A': 'Apple',
 'B': 'Ball',
 'C': 'Cat',
 'D': 'Dog',
 'E': 'Elephant',
 'F': 'Fan',
 'G': 'Glass'}

In [222]:
mapping=df["Letters"]
df

Letters      Words
0       A        Ant
1       B     Butter
2       C  Chocolate
3       D     Donkey
4       E        NaN
5       F        NaN
6       G        NaN

In [223]:
df['Mapped']=mapping.map(a)

In [224]:
df

Letters      Words    Mapped
0       A        Ant     Apple
1       B     Butter      Ball
2       C  Chocolate       Cat
3       D     Donkey       Dog
4       E        NaN  Elephant
5       F        NaN       Fan
6       G        NaN     Glass

In [225]:
ages=np.random.randint(15,60,20).astype(int)
bins=np.array([15,25,35,50,60]).astype(int)
level=["Teen","Adult","Middle Aged","Senior Citizen"]

In [226]:
print(ages)
pd.cut(ages,bins,labels=level)

[25 26 39 55 16 43 40 29 50 43 25 59 56 25 34 40 31 25 56 24]


[Teen, Adult, Middle Aged, Senior Citizen, Teen, ..., Middle Aged, Adult, Teen, Senior Citizen, Teen]
Length: 20
Categories (4, object): [Teen < Adult < Middle Aged < Senior Citizen]

In [227]:
data=np.random.rand(10)
data

array([0.73845642, 0.91642727, 0.95492444, 0.35819919, 0.24446941,
       0.30572562, 0.57187153, 0.09055155, 0.55833442, 0.46616859])

In [228]:
print(max(data),min(data))
pd.cut(data,4)

0.9549244362925826 0.0905515529707771


[(0.523, 0.739], (0.739, 0.955], (0.739, 0.955], (0.307, 0.523], (0.0897, 0.307], (0.0897, 0.307], (0.523, 0.739], (0.0897, 0.307], (0.523, 0.739], (0.307, 0.523]]
Categories (4, interval[float64]): [(0.0897, 0.307] < (0.307, 0.523] < (0.523, 0.739] < (0.739, 0.955]]

In [229]:
print(pd.cut(data,4,precision=1))
print(pd.cut(data,4,precision=2))
print(pd.cut(data,4,precision=3))
print(pd.cut(data,4,precision=4))
# this precision is used to display number of decimal values

[(0.5, 0.7], (0.7, 1.0], (0.7, 1.0], (0.3, 0.5], (0.09, 0.3], (0.09, 0.3], (0.5, 0.7], (0.09, 0.3], (0.5, 0.7], (0.3, 0.5]]
Categories (4, interval[float64]): [(0.09, 0.3] < (0.3, 0.5] < (0.5, 0.7] < (0.7, 1.0]]
[(0.52, 0.74], (0.74, 0.95], (0.74, 0.95], (0.31, 0.52], (0.09, 0.31], (0.09, 0.31], (0.52, 0.74], (0.09, 0.31], (0.52, 0.74], (0.31, 0.52]]
Categories (4, interval[float64]): [(0.09, 0.31] < (0.31, 0.52] < (0.52, 0.74] < (0.74, 0.95]]
[(0.523, 0.739], (0.739, 0.955], (0.739, 0.955], (0.307, 0.523], (0.0897, 0.307], (0.0897, 0.307], (0.523, 0.739], (0.0897, 0.307], (0.523, 0.739], (0.307, 0.523]]
Categories (4, interval[float64]): [(0.0897, 0.307] < (0.307, 0.523] < (0.523, 0.739] < (0.739, 0.955]]
[(0.5227, 0.7388], (0.7388, 0.9549], (0.7388, 0.9549], (0.3066, 0.5227], (0.08969, 0.3066], (0.08969, 0.3066], (0.5227, 0.7388], (0.08969, 0.3066], (0.5227, 0.7388], (0.3066, 0.5227]]
Categories (4, interval[float64]): [(0.08969, 0.3066] < (0.3066, 0.5227] < (0.5227, 0.7388] < (0.738

In [230]:
import matplotlib.pyplot as pl
data=np.random.randn(1000)
cats=pd.qcut(data,4)

In [231]:
cats

[(0.0329, 0.682], (0.0329, 0.682], (-3.162, -0.669], (-0.669, 0.0329], (0.682, 3.401], ..., (0.0329, 0.682], (-0.669, 0.0329], (-0.669, 0.0329], (-3.162, -0.669], (-3.162, -0.669]]
Length: 1000
Categories (4, interval[float64]): [(-3.162, -0.669] < (-0.669, 0.0329] < (0.0329, 0.682] < (0.682, 3.401]]

In [232]:
a=np.random.randn(1000)
np.mean(a).astype(int),np.var(a).astype(int)

(0, 1)

In [233]:
# Detecting and filtering outliers
data=pd.DataFrame(np.random.randint(-10,10,(10,4)))
data.describe()

0          1          2          3
count  10.000000  10.000000  10.000000  10.000000
mean   -2.300000  -1.500000  -1.000000  -4.900000
std     5.375872   6.450667   4.714045   3.871549
min   -10.000000  -8.000000 -10.000000 -10.000000
25%    -5.750000  -8.000000  -3.500000  -8.250000
50%    -2.000000  -1.500000  -0.500000  -5.000000
75%     1.000000   3.000000   2.000000  -1.250000
max     7.000000   9.000000   5.000000   0.000000

In [234]:
np.max(data,axis=0),np.max(data,axis=1)

(0    7
 1    9
 2    5
 3    0
 dtype: int32,
 0   -2
 1   -4
 2    3
 3    5
 4    1
 5    2
 6    9
 7    7
 8    2
 9    5
 dtype: int32)

In [235]:
col=data[2]
col[np.abs(col)>3]

1    -4
3     4
7   -10
8    -6
9     5
Name: 2, dtype: int32

In [236]:
data

0  1   2   3
0 -10 -8  -2 -10
1  -6 -8  -4  -4
2   1  3   2  -2
3   1  5   4 -10
4  -9  1  -2  -6
5  -5 -4   2  -1
6  -4  9   1  -6
7   7  3 -10   0
8   2 -8  -6  -1
9   0 -8   5  -9

In [237]:
np.sign(data)

0  1  2  3
0 -1 -1 -1 -1
1 -1 -1 -1 -1
2  1  1  1 -1
3  1  1  1 -1
4 -1  1 -1 -1
5 -1 -1  1 -1
6 -1  1  1 -1
7  1  1 -1  0
8  1 -1 -1 -1
9  0 -1  1 -1

In [238]:
df=pd.DataFrame(np.arange(5*4).reshape(5,4))
sampler=np.random.permutation(5)
sampler,df

(array([2, 4, 1, 0, 3]),
     0   1   2   3
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15
 4  16  17  18  19)

In [239]:
df.take(sampler)
# Take function displays df into permutation order 

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15

In [240]:
np.random.permutation(5)
# Permutation of n natural numbers

array([3, 0, 2, 4, 1])

In [241]:
df.take([1,1,1,1,1,1])

0  1  2  3
1  4  5  6  7
1  4  5  6  7
1  4  5  6  7
1  4  5  6  7
1  4  5  6  7
1  4  5  6  7

In [242]:
df.sample(n=3)
# takes random subset without replacement


0   1   2   3
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [243]:
df.sample(5)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11

In [244]:
choices=pd.Series([5,7,-1,6,4])
draws=choices.sample(n=10,replace=True)
draws

4    4
4    4
3    6
2   -1
2   -1
1    7
1    7
3    6
1    7
2   -1
dtype: int64

In [245]:
df=pd.DataFrame({'key':['b','b','a','c','a','b'],
                 'data1':range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [246]:
pd.get_dummies(df['key'])
# this maps a,b,c into indices 1 to 5.
# If a is available at index 0 its written as 1 else written as 0

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [247]:
pd.get_dummies(df['data1'])

0  1  2  3  4  5
0  1  0  0  0  0  0
1  0  1  0  0  0  0
2  0  0  1  0  0  0
3  0  0  0  1  0  0
4  0  0  0  0  1  0
5  0  0  0  0  0  1

In [248]:
dummies=pd.get_dummies(df['key'],prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [249]:
df_with_dummy=df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [250]:
a=pd.DataFrame({'x':['Animation|Childrens|Comedy','Adventure|Childrens|Fantasy',
   'Comedy|Romance','Comedy|Drama']})
all_generes=[]
for i in a.x:
    all_generes.extend(i.split('|'))
all_generes

['Animation',
 'Childrens',
 'Comedy',
 'Adventure',
 'Childrens',
 'Fantasy',
 'Comedy',
 'Romance',
 'Comedy',
 'Drama']

In [251]:
geners=pd.unique(all_generes)
geners

array(['Animation', 'Childrens', 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama'], dtype=object)

In [252]:
a=['Animation|Childrens|Comedy','Adventure|Childrens|Fantasy',
   'Comedy|Romance','Comedy|Drama']
lst1=[]
lst2=[]
for i in a:
    lst1.append(i.split('|'))
for i in a:
    lst2.extend(i.split('|'))
print(lst1,"\n")
print("\n",lst2)
# Append vs Extend

[['Animation', 'Childrens', 'Comedy'], ['Adventure', 'Childrens', 'Fantasy'], ['Comedy', 'Romance'], ['Comedy', 'Drama']] 


 ['Animation', 'Childrens', 'Comedy', 'Adventure', 'Childrens', 'Fantasy', 'Comedy', 'Romance', 'Comedy', 'Drama']


In [257]:
zero_matrix=np.zeros([5,5])
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [261]:
dummies=pd.DataFrame(zero_matrix,columns=["a",'b','c','d','e'])
dummies

a    b    c    d    e
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

In [264]:
print(a[0])
a[0].split('|')
# split('|') displayes the letters by splitting with symbol "|"

Animation|Childrens|Comedy


['Animation', 'Childrens', 'Comedy']

In [265]:
df=pd.read_csv('births.csv')
df.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

In [271]:
df.iloc[:10,3]

0    F
1    M
2    F
3    M
4    F
5    M
6    F
7    M
8    F
9    M
Name: gender, dtype: object

In [275]:
df[:10]

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548
5  1969      1  3.0      M    4994
6  1969      1  4.0      F    4440
7  1969      1  4.0      M    4520
8  1969      1  5.0      F    4192
9  1969      1  5.0      M    4198

In [283]:
np.random.seed(12334)
values=np.random.rand(10)
values

array([0.047532  , 0.57734709, 0.08591717, 0.81693052, 0.97774084,
       0.95141432, 0.01771613, 0.77352362, 0.79236102, 0.43857977])

In [284]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [286]:
a=pd.cut(values,bins)
a

[(0.0, 0.2], (0.4, 0.6], (0.0, 0.2], (0.8, 1.0], (0.8, 1.0], (0.8, 1.0], (0.0, 0.2], (0.6, 0.8], (0.6, 0.8], (0.4, 0.6]]
Categories (5, interval[float64]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [287]:
pd.get_dummies(a)

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           1           0           0           0           0
1           0           0           1           0           0
2           1           0           0           0           0
3           0           0           0           0           1
4           0           0           0           0           1
5           0           0           0           0           1
6           1           0           0           0           0
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           1           0           0

In [299]:
val='a,b,guido'
val2='a|b|guido'
val.split(","),val.split(),val2.split('|'),val2.split()

(['a', 'b', 'guido'], ['a,b,guido'], ['a', 'b', 'guido'], ['a|b|guido'])

In [301]:
pieces=[x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [302]:
'::'.join(pieces)

'a::b::guido'

In [304]:
'a' in pieces,'c' in pieces

(True, False)

In [319]:
val.find('0')

-1

In [323]:
val.count('p')

0

In [327]:
val.title(),val.lower(),val.upper()

('A,B,Guido', 'a,b,guido', 'A,B,GUIDO')