In [210]:
import json
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
from sklearn.linear_model import LogisticRegression
import random
import warnings
warnings.filterwarnings('ignore')

In [54]:
file=open('intents.json')

In [55]:
file=json.load(file)

In [56]:
file

{'intents': [{'tag': 'greeting',
   'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day'],
   'responses': ['Hello, thanks for visiting',
    'Good to see you again',
    'Hi there, how can I help?'],
   'context_set': ''},
  {'tag': 'goodbye',
   'patterns': ['Bye', 'See you later', 'Goodbye'],
   'responses': ['See you later, thanks for visiting',
    'Have a nice day',
    'Bye! Come back again soon.']},
  {'tag': 'thanks',
   'patterns': ['Thanks', 'Thank you', "That's helpful"],
   'responses': ['Happy to help!', 'Any time!', 'My pleasure']},
  {'tag': 'hours',
   'patterns': ['What hours are you open?',
    'What are your hours?',
    'When are you open?'],
   'responses': ["We're open every day 9am-9pm",
    'Our hours are 9am-9pm every day']},
  {'tag': 'location',
   'patterns': ['What is your location?',
    'Where are you located?',
    'What is your address?',
    'Where is your restaurant situated?'],
   'responses': ['We are on the intersection of Lon

In [60]:
corpus=[]
target=[]

for _,j in file.items():
    for k in range(len(j)):
        for l in j[k]['patterns']:
            corpus.append(l)
            target.append(j[k]['tag'])

In [65]:
corpus[:10],target[:10]

(['Hi',
  'How are you',
  'Is anyone there?',
  'Hello',
  'Good day',
  'Bye',
  'See you later',
  'Goodbye',
  'Thanks',
  'Thank you'],
 ['greeting',
  'greeting',
  'greeting',
  'greeting',
  'greeting',
  'goodbye',
  'goodbye',
  'goodbye',
  'thanks',
  'thanks'])

In [66]:
cv=CountVectorizer()
tv=TfidfVectorizer()

In [69]:
X_cv=cv.fit_transform(corpus)

In [70]:
X_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [71]:
X_tv=tv.fit_transform(corpus)

In [72]:
X_tv.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.38726899,
        0.        ],
       [0.        , 0.        , 0.65072693, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.15380829,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [74]:
X_cv.shape

(31, 58)

In [90]:
X_tv.shape

(31, 58)

In [96]:
target_encode=[[i] for i in target]
target_encode[:10]

[['greeting'],
 ['greeting'],
 ['greeting'],
 ['greeting'],
 ['greeting'],
 ['goodbye'],
 ['goodbye'],
 ['goodbye'],
 ['thanks'],
 ['thanks']]

In [78]:
enc=OneHotEncoder()

In [99]:
target_onehot=enc.fit_transform(target_encode).toarray()

In [101]:
target_onehot

array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0.

In [114]:
label_enc=LabelEncoder()
target_lebel=label_enc.fit_transform(target_encode)
target_lebel[:10]

C:\Users\rissu\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([2, 2, 2, 2, 2, 1, 1, 1, 7, 7], dtype=int64)

In [115]:
logistic=LogisticRegression()

In [116]:
logistic.fit(X_cv,target_lebel)

LogisticRegression()

In [117]:
logistic.score(X_cv,target_lebel)

1.0

In [202]:
def predict(text):
    transform=cv.transform(text).toarray()
    predicted=logistic.predict(transform)
    predicted=label_enc.inverse_transform([predicted])[0]
    for _,j in file.items():
        for k in range(len(j)):
            if j[k]['tag']==predicted:
                response=j[k]['responses']
                break
    return random.sample(response,1)

In [211]:
text=['What is your Menu?']
predict(text)

['You can check out the food menu at www.mymenu.com']

In [214]:
ask=str(input('Question:'))
ask=[ask]
predict(ask)

Question:where is raustarant located?


['Our Address is: 1000 Bridge Avenue, London EC3N 4AJ, UK']

In [215]:
logistic.fit(X_tv,target_lebel)
logistic.score(X_tv,target_lebel)

1.0

In [216]:
def predict_tv(text):
    transform=tv.transform(text).toarray()
    predicted=logistic.predict(transform)
    predicted=label_enc.inverse_transform([predicted])[0]
    for _,j in file.items():
        for k in range(len(j)):
            if j[k]['tag']==predicted:
                response=j[k]['responses']
                break
    return random.sample(response,1)

In [217]:
ask=str(input('Question:'))
ask=[ask]
predict(ask)

Question:What are you serving for today


["Today's special is Chicken Tikka"]

In [219]:
ask=str(input('Question:'))
ask=[ask]
predict(ask)

Question:is there anything new in todays menu


['You can check various delicacies given in the food menu at www.mymenu.com']