In [13]:
import numpy as np

In [16]:
a=np.array([1,5,2,7,8,2,0])
a

array([1, 5, 2, 7, 8, 2, 0])

In [17]:
a>5

array([False, False, False,  True,  True, False, False])

In [18]:
a<5

array([ True, False,  True, False, False,  True,  True])

In [19]:
a==5

array([False,  True, False, False, False, False, False])

In [20]:
a>=0

array([ True,  True,  True,  True,  True,  True,  True])

In [21]:
a<=0

array([False, False, False, False, False, False,  True])

In [22]:
a

array([1, 5, 2, 7, 8, 2, 0])

In [24]:
a[a>=5]

array([5, 7, 8])

In [25]:
a[a>0]

array([1, 5, 2, 7, 8, 2])

In [26]:
a[a!=5]

array([1, 2, 7, 8, 2, 0])

In [27]:
a

array([1, 5, 2, 7, 8, 2, 0])

In [31]:
np.count_nonzero(a==5)

1

In [32]:
a=np.random.randint(1,5,(3,4))
a

array([[3, 1, 3, 1],
       [1, 3, 4, 2],
       [4, 2, 1, 4]])

In [37]:
a

array([[3, 1, 3, 1],
       [1, 3, 4, 2],
       [4, 2, 1, 4]])

In [47]:
np.all(a>2,axis=1)

array([False, False, False])