In [27]:
import numpy as np

In [38]:
a=np.random.randint(1,10,(4,4))

In [39]:
a

array([[4, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [30]:
a.ndim

2

In [31]:
a.shape

(4, 4)

In [32]:
a[2][1]

4

In [33]:
a[2,1]

4

In [34]:
a=np.random.randint(1,10,10)

In [35]:
a

array([1, 7, 7, 3, 9, 9, 7, 2, 8, 4])

In [36]:
a[::-1]

array([4, 8, 2, 7, 9, 9, 3, 7, 7, 1])

In [40]:
a

array([[4, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [41]:
a[:,:2]

array([[4, 6],
       [6, 5],
       [9, 4],
       [2, 7]])

In [42]:
a[:,2:]

array([[6, 4],
       [8, 6],
       [9, 3],
       [8, 3]])

In [43]:
a

array([[4, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [44]:
a[:2,:]

array([[4, 6, 6, 4],
       [6, 5, 8, 6]])

In [45]:
a[2:,:]

array([[9, 4, 9, 3],
       [2, 7, 8, 3]])

In [46]:
a

array([[4, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [47]:
a[:2,:2]

array([[4, 6],
       [6, 5]])

In [48]:
a

array([[4, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [51]:
a=b

In [52]:
b

array([[4, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [54]:
b[0,0]=0

In [55]:
b

array([[0, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [57]:
a

array([[0, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [58]:
a

array([[0, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [60]:
b=a.copy()

In [61]:
b

array([[0, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [63]:
b[0,0]=1

In [64]:
b

array([[1, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])

In [65]:
a

array([[0, 6, 6, 4],
       [6, 5, 8, 6],
       [9, 4, 9, 3],
       [2, 7, 8, 3]])