In [1]:
import numpy as np

In [19]:
a=np.array([1,2,4,3,4])

In [20]:
np.add(a,5)

array([6, 7, 9, 8, 9])

In [21]:
np.subtract(a,2)

array([-1,  0,  2,  1,  2])

In [22]:
np.multiply(a,5)

array([ 5, 10, 20, 15, 20])

In [23]:
np.divide(a,3)

array([0.33333333, 0.66666667, 1.33333333, 1.        , 1.33333333])

In [25]:
np.power(a,2)

array([ 1,  4, 16,  9, 16], dtype=int32)

In [27]:
a=np.array([1,-1,2,-2,3,-3])

In [29]:
a

array([ 1, -1,  2, -2,  3, -3])

In [30]:
np.abs(a)

array([1, 1, 2, 2, 3, 3])

In [31]:
a=np.linspace(1,5,10)

In [32]:
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.sin(a)

array([ 0.84147098,  0.99202822,  0.94983371,  0.72308588,  0.35584199,
       -0.08054223, -0.50127705, -0.8246134 , -0.98772683, -0.95892427])

In [36]:
np.cos(a)

array([ 0.54030231,  0.12601595, -0.31275538, -0.69075814, -0.93454613,
       -0.9967512 , -0.86528684, -0.56569668, -0.15619128,  0.28366219])

In [37]:
np.tan(a)

array([ 1.55740772,  7.87224305, -3.03698597, -1.04680038, -0.3807645 ,
        0.08080475,  0.57931893,  1.45769531,  6.32382808, -3.38051501])

In [45]:
np.cos(45)

0.5253219888177297

In [46]:
np.exp(10)

22026.465794806718

In [47]:
np.exp(1)

2.718281828459045

In [48]:
np.log(1)

0.0

In [49]:
np.log(0)

C:\Users\rissu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [50]:
np.log10(10)

1.0

In [55]:
np.log2(32)

5.0