In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [10]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [11]:
a=np.arange(1,50,5)
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [12]:
a=np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [13]:
a=np.linspace(1,10,10)

In [14]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
a=np.random.rand(1)
a

array([0.12330968])

In [56]:
a=np.random.randint(100)
a

46

In [58]:
a=np.random.randn(10)
a

array([-0.29505127, -0.08346434,  1.59720034,  1.13895767, -0.47714321,
       -0.74855419, -0.3295586 , -0.49407864, -0.55278087, -0.48240078])

In [59]:
a=np.zeros(10)

In [60]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
a=np.full(5,4)
a

array([4, 4, 4, 4, 4])

In [65]:
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [67]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])