In [1]:
import numpy as np

In [2]:
a=np.array([1,33,2,4,5])

In [4]:
a

array([ 1, 33,  2,  4,  5])

In [7]:
b=np.empty(5)
b

array([1.61323712e-307, 4.67296746e-307, 1.69121096e-306, 1.69119873e-306,
       3.44902066e-307])

In [8]:
np.multiply(a,2,out=b)

array([ 2., 66.,  4.,  8., 10.])

In [9]:
b

array([ 2., 66.,  4.,  8., 10.])

In [10]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.sum(a)

45

In [12]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [13]:
np.add.reduce(a)

45

In [14]:
a=np.random.randint(1,10,10)
a

array([2, 1, 9, 9, 1, 7, 8, 6, 1, 9])

In [15]:
np.min(a)

1

In [16]:
np.max(a)

9

In [25]:
a=np.random.randint(1,10,(3,5))
a

array([[1, 1, 6, 8, 6],
       [5, 2, 3, 5, 8],
       [8, 6, 2, 7, 5]])

In [18]:
np.max(a,axis=1)

array([9, 9, 8])

In [19]:
np.max(a,axis=0)

array([5, 6, 9, 9, 6])

In [20]:
a=np.random.randint(1,10,10)
a

array([8, 5, 4, 7, 9, 3, 1, 9, 5, 4])

In [21]:
np.max(a)

9

In [22]:
np.argmax(a)

4

In [24]:
np.argmin(a)

6

In [26]:
a

array([[1, 1, 6, 8, 6],
       [5, 2, 3, 5, 8],
       [8, 6, 2, 7, 5]])

In [27]:
np.mean(a,axis=1)

array([4.4, 4.6, 5.6])

In [29]:
np.mean(a,axis=0)

array([4.66666667, 3.        , 3.66666667, 6.66666667, 6.33333333])

In [31]:
np.median(a,axis=0)

array([5., 2., 3., 7., 6.])

In [32]:
np.median(a,axis=1)

array([6., 5., 6.])

In [34]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])