In [1]:
import numpy as np

In [18]:
np.random.seed(0)
x=np.random.randint(1,5,10)
x

array([1, 4, 2, 1, 4, 4, 4, 4, 2, 4])

In [17]:
rand=np.random.RandomState(0)
x=rand.randint(1,5,10)
x

array([1, 4, 2, 1, 4, 4, 4, 4, 2, 4])

In [32]:
x=np.random.randint(1,5,10)

In [20]:
x

array([2, 3, 1, 4, 3, 1, 1, 1, 3, 2])

In [24]:
index=[1,3,7]

In [ ]:
3,4,1

In [25]:
x[index]

array([3, 4, 1])

In [42]:
x=np.random.randint(1,5,12).reshape(3,4)
x

array([[2, 1, 4, 1],
       [4, 2, 3, 4],
       [4, 1, 3, 4]])

In [30]:
row=[0,2]
col=[1,3]

In [31]:
x[row,col]

array([ 1, 11])

In [33]:
x

array([3, 4, 4, 3, 1, 2, 2, 2, 2, 1])

In [35]:
np.sort(x)[::-1]

array([4, 4, 3, 3, 2, 2, 2, 2, 1, 1])

In [38]:
np.sort(x,kind='heapsort')

array([1, 1, 2, 2, 2, 2, 3, 3, 4, 4])

In [46]:
x

array([[2, 1, 4, 1],
       [4, 2, 3, 4],
       [4, 1, 3, 4]])

array([[1, 1, 2, 4],
       [2, 3, 4, 4],
       [1, 3, 4, 4]])

In [47]:
np.sort(x,axis=0)

array([[2, 1, 3, 1],
       [4, 1, 3, 4],
       [4, 2, 4, 4]])

In [49]:
np.sort(x,axis=1)

array([[1, 1, 2, 4],
       [2, 3, 4, 4],
       [1, 3, 4, 4]])