In [1]:
import numpy as np

In [19]:
a=np.random.randint(1,10,size=(3,3))
a

array([[1, 8, 6],
       [5, 6, 1],
       [5, 8, 8]])

In [20]:
a.shape

(3, 3)

In [21]:
a.ndim

2

In [22]:
a.size

9

In [23]:
a.dtype

dtype('int32')

In [26]:
b=a.astype(np.float)
b

array([[1., 8., 6.],
       [5., 6., 1.],
       [5., 8., 8.]])

In [27]:
b.dtype

dtype('float64')

In [30]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
a[0]

10

In [32]:
a[4]

14

In [33]:
a[-1]

19

In [34]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
a[:5]

array([10, 11, 12, 13, 14])

In [36]:
a[5:]

array([15, 16, 17, 18, 19])

In [37]:
a[3:6]

array([13, 14, 15])

In [38]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
a[-2]

18

In [40]:
a[-4]

16