# Scientific computation

Python List

Typical List example

In [38]:
a=[1,2,3]
print(a)

[1, 2, 3]


In [23]:
b=['a','b','c']
print(b)

['a', 'b', 'c']


In [39]:
a+a

[1, 2, 3, 1, 2, 3]

problem with list

In [26]:
for i in a:
    print(i+1)

2
3
4


installing libraries

In [27]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [28]:
a

[1, 2, 3]

In [30]:
import numpy

solution to list

In [32]:
a=numpy.array([1,2,3])
print(a)

[1 2 3]


In [33]:
a+1

array([2, 3, 4])

In [34]:
a*5

array([ 5, 10, 15])

In [35]:
import numpy as np

In [40]:
a=np.array([1,2,3])

In [42]:
a+a

array([2, 4, 6])