In [70]:
import numpy as np

In [139]:
a=np.random.randint(1,10,9)

In [140]:
a

array([2, 7, 8, 4, 3, 9, 5, 6, 7])

In [141]:
len(a)

9

In [142]:
a.reshape(3,3)

array([[2, 7, 8],
       [4, 3, 9],
       [5, 6, 7]])

In [149]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,10)

In [150]:
a,b

(array([5, 3, 8, 8, 2, 6, 5, 7, 9, 4]), array([1, 6, 1, 5, 4, 9, 4, 6, 1, 7]))

In [160]:
c=np.concatenate([a,b])

In [158]:
c.shape

(20,)

In [153]:
c=np.vstack([a,b])

In [154]:
c

array([[5, 3, 8, 8, 2, 6, 5, 7, 9, 4],
       [1, 6, 1, 5, 4, 9, 4, 6, 1, 7]])

In [161]:
c

array([5, 3, 8, 8, 2, 6, 5, 7, 9, 4, 1, 6, 1, 5, 4, 9, 4, 6, 1, 7])

In [166]:
np.split(c,[3,10])

[array([5, 3, 8]),
 array([8, 2, 6, 5, 7, 9, 4]),
 array([1, 6, 1, 5, 4, 9, 4, 6, 1, 7])]

In [167]:
a=np.random.randint(1,10,(4,4))

In [168]:
a

array([[4, 9, 4, 1],
       [2, 4, 9, 3],
       [1, 6, 5, 5],
       [7, 1, 9, 4]])

In [169]:
np.hsplit(a,[2])

[array([[4, 9],
        [2, 4],
        [1, 6],
        [7, 1]]),
 array([[4, 1],
        [9, 3],
        [5, 5],
        [9, 4]])]

In [171]:
np.vsplit(a,[1,3])

[array([[4, 9, 4, 1]]),
 array([[2, 4, 9, 3],
        [1, 6, 5, 5]]),
 array([[7, 1, 9, 4]])]