In [1]:
import numpy as np
import pandas as pd

In [3]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [32]:
arr=np.arange(9).reshape(-1,3)
ar2=np.ones((3,3))
arr,ar2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [33]:
np.outer(arr,ar2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [34]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
s1,s2,s3

(a    0
 b    1
 dtype: int64,
 c    2
 d    3
 e    4
 dtype: int64,
 f    5
 g    6
 dtype: int64)

In [40]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [41]:
pd.concat([s1,s2,s3],axis=0)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [43]:
s4=pd.concat([s1,s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [47]:
pd.concat([s1,s2,s3,s4],join='outer')

a    0
b    1
c    2
d    3
e    4
f    5
g    6
a    0
b    1
f    5
g    6
dtype: int64

In [57]:
# pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']])

In [68]:
result=pd.concat([s1,s2,s3],axis=0,keys=[1,2,3])
result

1  a    0
   b    1
2  c    2
   d    3
   e    4
3  f    5
   g    6
dtype: int64

In [70]:
result.unstack()

a    b    c    d    e    f    g
1  0.0  1.0  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  2.0  3.0  4.0  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  5.0  6.0

In [71]:
result=pd.concat([s1,s2,s3],axis=1,keys=[1,2,3])
result

1    2    3
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [73]:
result.unstack()

1  a    0.0
   b    1.0
   c    NaN
   d    NaN
   e    NaN
   f    NaN
   g    NaN
2  a    NaN
   b    NaN
   c    2.0
   d    3.0
   e    4.0
   f    NaN
   g    NaN
3  a    NaN
   b    NaN
   c    NaN
   d    NaN
   e    NaN
   f    5.0
   g    6.0
dtype: float64

In [79]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2),index=['a', 'c'],
columns=['three', 'four'])
df1

one  two
a    0    1
b    2    3
c    4    5

In [80]:
df2

three  four
a      5     6
c      7     8

In [81]:
pd.concat([df1,df2],axis=0)

one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [78]:
pd.concat([df1,df2],axis=1)

one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [84]:
pd.concat([df1,df2],axis=1).unstack()

one    a    0.0
       b    2.0
       c    4.0
two    a    1.0
       b    3.0
       c    5.0
three  a    5.0
       b    NaN
       c    7.0
four   a    6.0
       b    NaN
       c    8.0
dtype: float64

In [85]:
pd.concat([df1,df2],axis=1).stack()

a  one      0.0
   two      1.0
   three    5.0
   four     6.0
b  one      2.0
   two      3.0
c  one      4.0
   two      5.0
   three    7.0
   four     8.0
dtype: float64

In [88]:
pd.concat([df1,df2],axis=0,keys=['level1','level2'])

one  two  three  four
level1 a  0.0  1.0    NaN   NaN
       b  2.0  3.0    NaN   NaN
       c  4.0  5.0    NaN   NaN
level2 a  NaN  NaN    5.0   6.0
       c  NaN  NaN    7.0   8.0

In [92]:
a=pd.concat([df1,df2],axis=1,keys=['level1','level2'])
a

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [98]:
a.keys(),a.columns

(MultiIndex([('level1',   'one'),
             ('level1',   'two'),
             ('level2', 'three'),
             ('level2',  'four')],
            ),
 MultiIndex([('level1',   'one'),
             ('level1',   'two'),
             ('level2', 'three'),
             ('level2',  'four')],
            ))

In [101]:
a['level1']

one  two
a    0    1
b    2    3
c    4    5

In [102]:
a['level2']

three  four
a    5.0   6.0
b    NaN   NaN
c    7.0   8.0

In [110]:
pd.concat({'level1':df1,
           'level2':df2},axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [111]:
pd.concat({'level1':df1,
           'level2':df2},axis=0)

one  two  three  four
level1 a  0.0  1.0    NaN   NaN
       b  2.0  3.0    NaN   NaN
       c  4.0  5.0    NaN   NaN
level2 a  NaN  NaN    5.0   6.0
       c  NaN  NaN    7.0   8.0

In [114]:
a=pd.concat([df1,df2],axis=1,keys=['level1','level2'],
          names=['upper','lower'])
a

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [119]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [121]:
df1

a         b         c         d
0  0.705609  0.768449  0.130622 -1.223339
1 -0.943422 -2.740756 -1.468017 -0.034914
2 -0.079851  1.764534 -0.335263 -0.257258

In [122]:
df2

b         d        a
0  1.527138 -0.364984  0.61820
1  0.782069  0.393672  1.48951

In [128]:
pd.concat([df1,df2])
# Without Ignore_index

a         b         c         d
0  0.705609  0.768449  0.130622 -1.223339
1 -0.943422 -2.740756 -1.468017 -0.034914
2 -0.079851  1.764534 -0.335263 -0.257258
0  0.618200  1.527138       NaN -0.364984
1  1.489510  0.782069       NaN  0.393672

In [129]:
pd.concat([df1,df2],ignore_index=True)
# After Ignore_index

a         b         c         d
0  0.705609  0.768449  0.130622 -1.223339
1 -0.943422 -2.740756 -1.468017 -0.034914
2 -0.079851  1.764534 -0.335263 -0.257258
3  0.618200  1.527138       NaN -0.364984
4  1.489510  0.782069       NaN  0.393672