In [1]:
import numpy as np
import pandas as pd

In [3]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [32]:
arr=np.arange(9).reshape(-1,3)
ar2=np.ones((3,3))
arr,ar2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [33]:
np.outer(arr,ar2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [34]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
s1,s2,s3

(a    0
 b    1
 dtype: int64,
 c    2
 d    3
 e    4
 dtype: int64,
 f    5
 g    6
 dtype: int64)

In [40]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [41]:
pd.concat([s1,s2,s3],axis=0)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [43]:
s4=pd.concat([s1,s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [47]:
pd.concat([s1,s2,s3,s4],join='outer')

a    0
b    1
c    2
d    3
e    4
f    5
g    6
a    0
b    1
f    5
g    6
dtype: int64

In [57]:
# pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']])

In [68]:
result=pd.concat([s1,s2,s3],axis=0,keys=[1,2,3])
result

1  a    0
   b    1
2  c    2
   d    3
   e    4
3  f    5
   g    6
dtype: int64

In [70]:
result.unstack()

a    b    c    d    e    f    g
1  0.0  1.0  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  2.0  3.0  4.0  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  5.0  6.0

In [71]:
result=pd.concat([s1,s2,s3],axis=1,keys=[1,2,3])
result

1    2    3
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [73]:
result.unstack()

1  a    0.0
   b    1.0
   c    NaN
   d    NaN
   e    NaN
   f    NaN
   g    NaN
2  a    NaN
   b    NaN
   c    2.0
   d    3.0
   e    4.0
   f    NaN
   g    NaN
3  a    NaN
   b    NaN
   c    NaN
   d    NaN
   e    NaN
   f    5.0
   g    6.0
dtype: float64