In [20]:
import numpy as np
arr=np.empty((8,4))

In [32]:
for i in range(8):
    arr[i]==i

In [33]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [77]:
arr = np.empty((8, 4))

In [78]:
for i in range(8):
    arr[i] = i

In [79]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [80]:
arr[[1,2,3]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [81]:
arr[[1,2,3,6,7]][:,[1,3,2]]
arr.shape

(8, 4)

In [82]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [103]:
arr=np.arange(16).reshape(2,2,4)
print(arr)
arr.transpose((1,0,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [112]:
arr.swapaxes(2,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [120]:
a=np.random.rand(10)
b=np.random.rand(10)
a,b

(array([0.74166317, 0.2332427 , 0.75887356, 0.32740994, 0.45248436,
        0.54543871, 0.55116437, 0.83221471, 0.11201843, 0.03853472]),
 array([0.1081451 , 0.36816981, 0.97601005, 0.49743833, 0.81446901,
        0.9211557 , 0.5331047 , 0.18394331, 0.27468355, 0.19999787]))

In [147]:
np.maximum(a,b)
arr=np.random.randn(7)*5
arr

array([  0.72496463,   8.70702871,  -2.7120416 ,   0.4569504 ,
       -11.22448984,   7.72290981,   0.35625242])

In [148]:
reminder,whole=np.modf(arr)
reminder,whole

(array([ 0.72496463,  0.70702871, -0.7120416 ,  0.4569504 , -0.22448984,
         0.72290981,  0.35625242]),
 array([  0.,   8.,  -2.,   0., -11.,   7.,   0.]))

In [149]:
np.sqrt(arr)

C:\Users\RINSU\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.85144855, 2.95076748,        nan, 0.67598107,        nan,
       2.77901238, 0.59686884])

In [150]:
np.sqrt(arr,arr)

C:\Users\RINSU\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.85144855, 2.95076748,        nan, 0.67598107,        nan,
       2.77901238, 0.59686884])

In [152]:
np.sqrt(4,4)

TypeError: return arrays must be of ArrayType