In [25]:
a=list(range(10))
print(a*3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [29]:
import numpy as np
a=np.arange(10,dtype='float32')
print(a*3)

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]


In [31]:
a.dtype

dtype('float32')

In [34]:
a=a.reshape(-1,2)
a.ndim

2

In [37]:
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

In [12]:
import numpy as np
a=np.arange(10)
a
a=a.astype('float32')
a.dtype

dtype('float32')

In [22]:
a=np.array(['a','b','c','d'])
b=np.random.randint(1,10,(4,4))
b

array([[5, 7, 5, 4],
       [4, 4, 2, 6],
       [9, 1, 2, 9],
       [8, 3, 5, 1]])

In [26]:
b[a=='d']

array([[8, 3, 5, 1]])

In [33]:
cond=(a=='c')
b[~cond]

array([[5, 7, 5, 4],
       [4, 4, 2, 6],
       [8, 3, 5, 1]])

In [38]:
cond=((a=='a')|(a=='c'))
b[~cond]

array([[4, 4, 2, 6],
       [8, 3, 5, 1]])