In [2]:
import numpy as np


In [6]:
a=np.array([[0,0],[0,1],[1,0],[1,1]])
a

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [57]:
def calculate_error(a,w0,w1,w2):
    weight=np.array([[w1],[w2]])
    val=np.dot(a,weight)+w0
    if val[0]<0:
        val[0]=0
    if val[1]>=0:
        val[1]=1
    else:
        val[1]=0
    if val[2]>=0:
        val[2]=1
    else:
        val[2]=0
    if val[3]>=0:
        val[3]=1   
    return (val).astype(int)
    
print("_________________\nOriginal:\n",np.array([[0],[1],[1],[1]]))
print("Predicted:\n",calculate_error(a,-1,-1,-1))


_________________
Original:
 [[0]
 [1]
 [1]
 [1]]
Predicted:
 [[ 0]
 [ 0]
 [-2]
 [-3]]


In [41]:
x=np.array(calculate_error(a,-1,1.1,1.1))