In [3]:
import tensorflow as tf
import numpy as np

In [5]:
tensor_2=tf.constant([[23,4],[32,51]])

In [14]:
tensor_2.numpy()

array([[23,  4],
       [32, 51]])

In [15]:
numpy_tensor=np.array([[23,4],[32,51]])

In [17]:
tensor_from_numpy=tf.constant(numpy_tensor)

In [29]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [30]:
tf_var=tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [31]:
tf_var.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [33]:
tf_var[0,2].assign(50)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1.,  2., 50.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [34]:
tf_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1.,  2., 50.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [35]:
tensor=tf.constant([[1,2],[3,4]])

In [39]:
tensor.numpy(),tensor.numpy()+5

(array([[1, 2],
        [3, 4]]),
 array([[6, 7],
        [8, 9]]))

In [40]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [43]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [44]:
np.dot(tensor,tensor)

array([[ 7, 10],
       [15, 22]])

In [62]:
tf_string=tf.constant('aTensorflow')

In [63]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'aTensorflow'>

In [64]:
tf.strings.unicode_decode(tf_string,'UTF8')

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 97,  84, 101, 110, 115, 111, 114, 102, 108, 111, 119])>

In [65]:
tf_array=tf.constant(['Rishav','Paudel','Neeshu','Jyotshu'])

In [66]:
for i in tf_array:
    print(i)

tf.Tensor(b'Rishav', shape=(), dtype=string)
tf.Tensor(b'Paudel', shape=(), dtype=string)
tf.Tensor(b'Neeshu', shape=(), dtype=string)
tf.Tensor(b'Jyotshu', shape=(), dtype=string)
