In [57]:
import numpy as np
np.random.seed(0)

x1=np.random.randint(10,size=6)
print(x1,"\n")

x2=np.random.randint(1,10,(6))
print(x2,"\n")

x3=np.random.randint(1,10,(3,3))
print(x3,"\n")

x4=np.random.randint(10,size=(3,4))
print(x4,"\n------------------------")

x5=np.random.randint(100,size=(3,3,5))
print(x5)

[5 0 3 3 7 9] 

[4 6 3 5 8 7] 

[[9 9 2]
 [7 8 8]
 [9 2 6]] 

[[9 8 9 4]
 [3 0 3 5]
 [0 2 3 8]] 
------------------------
[[[49 29 19 19 14]
  [39 32 65  9 57]
  [32 31 74 23 35]]

 [[75 55 28 34  0]
  [ 0 36 53  5 38]
  [17 79  4 42 58]]

 [[31  1 65 41 57]
  [35 11 46 82 91]
  [ 0 14 99 53 12]]]


In [42]:
print("X1->",x1.ndim,x1.shape,x1.size,x1.dtype)
print("X2->",x2.ndim,x2.shape,x2.size,x2.dtype)
print("X3->",x3.ndim,x3.shape,x3.size,x3.dtype)
print("X4->",x4.ndim,x4.shape,x4.size,x4.dtype)
print("X5->",x5.ndim,x5.shape,x5.size,x5.dtype)


X1-> 1 (6,) 6 int32
X2-> 1 (6,) 6 int32
X3-> 2 (3, 3) 9 int32
X4-> 2 (3, 4) 12 int32
X5-> 3 (3, 3, 5) 45 int32


In [58]:
print(x2.itemsize)

4


In [62]:
x5[0,1]

array([39, 32, 65,  9, 57])

In [67]:
x5[0,1,1]

32

In [121]:
x3=np.array([1,2,5,3,1,4,7,76,4,2])
print(x3,"\n")
print(x3.size)

[ 1  2  5  3  1  4  7 76  4  2] 

10


In [126]:
print(x3[5::-1])
x3[9:4:-1] 

[4 1 3 5 2 1]


array([ 2,  4, 76,  7,  4])

In [128]:
x5

array([[[49, 29, 19, 19, 14],
        [39, 32, 65,  9, 57],
        [32, 31, 74, 23, 35]],

       [[75, 55, 28, 34,  0],
        [ 0, 36, 53,  5, 38],
        [17, 79,  4, 42, 58]],

       [[31,  1, 65, 41, 57],
        [35, 11, 46, 82, 91],
        [ 0, 14, 99, 53, 12]]])

In [142]:
x5[::,::,::-1]

array([[[14, 19, 19, 29, 49],
        [57,  9, 65, 32, 39],
        [35, 23, 74, 31, 32]],

       [[ 0, 34, 28, 55, 75],
        [38,  5, 53, 36,  0],
        [58, 42,  4, 79, 17]],

       [[57, 41, 65,  1, 31],
        [91, 82, 46, 11, 35],
        [12, 53, 99, 14,  0]]])

In [173]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x,"\n-----------------------")
print(x[1:3,:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
-----------------------
[[ 5  6]
 [ 9 10]]


In [189]:
a=np.array(range(16)).reshape(4,4)
a
b=a.copy()
b[2,1]=100
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8 100  10  11]
 [ 12  13  14  15]]


In [205]:
a[a%2==0]
a

array([[ 1,  1,  1,  3],
       [ 1,  5,  1,  7],
       [ 1,  9,  1, 11],
       [ 1, 13,  1, 15]])

In [228]:
a=np.array(range(10)).reshape(2,5)
b=np.array(range(10,20)).reshape(2,5)
print(" A is:\n",a,"\n--------------\n","B is:\n",b,"\n")

# row concatenate
np.concatenate([a,b],axis=1)


 A is:
 [[0 1 2 3 4]
 [5 6 7 8 9]] 
--------------
 B is:
 [[10 11 12 13 14]
 [15 16 17 18 19]] 



array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [231]:
#column concatenate 
np.concatenate([a,b],axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [234]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [235]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [239]:
np.vstack([a,b])
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [287]:
np.random.seed(0)
def compute_reciprocals(values):
    print(values)
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output
values=np.random.randint(1,10,size=5)
a=compute_reciprocals(values)    
a

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [292]:
big_array=np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

[79 11 71 ... 58 51 56]
[79 11 71 ... 58 51 56]
[79 11 71 ... 58 51 56]
[79 11 71 ... 58 51 56]
[79 11 71 ... 58 51 56]
[79 11 71 ... 58 51 56]
[79 11 71 ... 58 51 56]
[79 11 71 ... 58 51 56]
2.4 s ± 20.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [308]:
n=np.random.randint(1,100,size=(4,25))
n*5

array([[255,  50, 390,  20, 490, 220, 285,  50,  70, 370, 110, 375, 370,
        235, 250, 420, 300, 375, 165, 235, 320, 215, 190, 430, 135],
       [170,  85, 475, 475, 450, 460,  65, 375, 430, 455, 260, 440, 385,
        270, 355,  90,  45, 300, 175, 250, 460, 165, 360, 200, 380],
       [ 65,  70, 365, 105, 135, 335, 440, 250, 285,  60,  75,  50,  50,
         35, 175, 145,  90, 345, 190, 220, 365, 175, 255, 425, 395],
       [460,  10, 255, 290, 160, 245,  10, 405, 305, 260, 300, 255, 490,
        210, 315, 395, 360, 440, 260,  60,  30, 190,  20,  20, 235]])

In [327]:
np.random.seed(0)
n=np.random.randint(1,10,size=(3,3))
print(n**2)
print(n//2)


[[36  1 16]
 [16 64 16]
 [36  9 25]]
[[3 0 2]
 [2 4 2]
 [3 1 2]]


In [332]:
# abs converts negative values into positive values....
a=np.array(range(-10,10))
print(a)
print(abs(a))

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
[10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9]


In [336]:
np.absolute(a)


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [338]:
np.abs(a)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [346]:
theta=np.linspace(0,np.pi,3)
theta


array([0.        , 1.57079633, 3.14159265])

In [350]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [352]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [353]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [357]:
theta=[-1,0,1]
np.arcsin(theta)

array([-1.57079633,  0.        ,  1.57079633])

In [360]:
np.arccos(theta)

array([3.14159265, 1.57079633, 0.        ])

In [363]:
a=[1,2,3]
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [365]:
np.exp2(a)

array([2., 4., 8.])

In [369]:
# [1,2,3] power of 3
np.power(a,3)

array([ 1,  8, 27], dtype=int32)

In [372]:
# 3 power of [1,2,3]
np.power(3,a)

array([ 3,  9, 27], dtype=int32)

In [383]:
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)

array([ 0., 10., 20., 30., 40.])

In [404]:
y=np.empty(5)
np.power(2,x,out=y[::1])
y

array([ 1.,  2.,  4.,  8., 16.])

In [406]:
x=np.arange(1,6)
np.add.reduce(x)

15

In [408]:

np.multiply.reduce(x)

120

In [412]:
np.divide(x,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [414]:
np.add.accumulate(x)


array([ 1,  3,  6, 10, 15], dtype=int32)

In [416]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [475]:
x=np.arange(1,6)
print(np.multiply.outer(x,x))
np.multiply.outer(x,[2,3,4,5,6,7,8,9])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  6,  8, 10, 12, 14, 16, 18],
       [ 6,  9, 12, 15, 18, 21, 24, 27],
       [ 8, 12, 16, 20, 24, 28, 32, 36],
       [10, 15, 20, 25, 30, 35, 40, 45]])

In [476]:
np.random.seed(0)
a=np.random.randint(1,5,[4,4])
print(a)
sum(a)

[[1 4 2 1]
 [4 4 4 4]
 [2 4 2 3]
 [1 4 3 1]]


array([ 8, 16, 11,  9])

In [495]:
np.random.seed(0)
a=np.random.randint(1,100000,(8,8))
a

array([[68269, 43568, 42614, 45892, 21244, 95940, 97640, 41994],
       [86294, 55027, 80472, 80967, 48601, 39513, 52621, 80187],
       [17090, 32231, 18984, 89689, 82458, 93006,  6922, 38805],
       [67700, 70609, 37620,  7878, 83967,  1872, 73136,  2497],
       [47955, 24676, 31922, 99060,   798, 49812, 68756, 80783],
       [90536, 81858, 52490, 84666, 41505, 49867, 84213, 96767],
       [11724, 43891, 17592, 58147, 92289, 59301, 89142, 71558],
       [20007,  3561, 90869, 61714, 96592, 45445, 46523, 86905]])

In [513]:
np.min(a),np.max(a),np.sum(a),np.multiply.reduce(a),np.add.reduce(a)


(798,
 99060,
 3586231,
 array([ 1605280256,   332695168,  -919617536,   762164096, -1552267520,
         1367435776, -1215891456,   307620100]),
 array([409575, 355421, 372563, 528013, 467454, 434756, 518953, 499496]))

In [523]:
a=np.random.random((4,4))
print(a)
print(a.sum())
print(a.size)
print(a.shape)
print(a.ndim)

[[0.71158382 0.15369431 0.73044218 0.64626444]
 [0.21488074 0.18645822 0.80758027 0.74707947]
 [0.67484735 0.27689375 0.17490887 0.70447426]
 [0.4631502  0.84042853 0.20486576 0.16495887]]
7.702511023429581
16
(4, 4)
2


In [536]:

print(np.min(a,axis=0))
print(np.min(a,axis=1))
b=np.multiply.outer(a,a)
b

[0.21488074 0.15369431 0.17490887 0.16495887]
[0.15369431 0.18645822 0.17490887 0.16495887]


array([[[[0.50635153, 0.10936638, 0.51977083, 0.45987132],
         [0.15290565, 0.13268065, 0.57466105, 0.53160966],
         [0.48021045, 0.19703311, 0.12446232, 0.50129248],
         [0.32957019, 0.59803534, 0.14577916, 0.11738206]],

        [[0.10936638, 0.02362194, 0.1122648 , 0.09932716],
         [0.03302595, 0.02865757, 0.12412049, 0.11482186],
         [0.10372019, 0.04255699, 0.0268825 , 0.10827368],
         [0.07118355, 0.12916908, 0.0314867 , 0.02535324]],

        [[0.51977083, 0.1122648 , 0.53354577, 0.4720588 ],
         [0.15695795, 0.13619695, 0.58989069, 0.54569835],
         [0.49293696, 0.20225487, 0.12776082, 0.51457771],
         [0.33830444, 0.61388445, 0.14964259, 0.12049291]],

        [[0.45987132, 0.09932716, 0.4720588 , 0.41765772],
         [0.13886978, 0.12050132, 0.52191041, 0.48281089],
         [0.43612984, 0.17894658, 0.11303739, 0.45527666],
         [0.2993175 , 0.54313907, 0.13239746, 0.10660705]]],


       [[[0.15290565, 0.03302595, 0.15695795, 

In [541]:
np.min(b,axis=0)

array([[[0.15290565, 0.03302595, 0.15695795, 0.13886978],
        [0.04617373, 0.04006628, 0.17353344, 0.16053299],
        [0.14501169, 0.05949913, 0.03758455, 0.15137795],
        [0.09952206, 0.1805919 , 0.04402171, 0.03544648]],

       [[0.10936638, 0.02362194, 0.1122648 , 0.09932716],
        [0.03302595, 0.02865757, 0.12412049, 0.11482186],
        [0.10372019, 0.04255699, 0.0268825 , 0.10827368],
        [0.07118355, 0.12916908, 0.0314867 , 0.02535324]],

       [[0.12446232, 0.0268825 , 0.12776082, 0.11303739],
        [0.03758455, 0.0326132 , 0.14125296, 0.13067083],
        [0.11803679, 0.04843117, 0.03059311, 0.1232188 ],
        [0.08100908, 0.14699841, 0.03583284, 0.02885277]],

       [[0.11738206, 0.02535324, 0.12049291, 0.10660705],
        [0.03544648, 0.03075794, 0.13321753, 0.12323738],
        [0.11132205, 0.04567608, 0.02885277, 0.11620928],
        [0.07640073, 0.13863614, 0.03379442, 0.02721143]]])

In [544]:
np.min(b,axis=1)

array([[[0.10936638, 0.02362194, 0.1122648 , 0.09932716],
        [0.03302595, 0.02865757, 0.12412049, 0.11482186],
        [0.10372019, 0.04255699, 0.0268825 , 0.10827368],
        [0.07118355, 0.12916908, 0.0314867 , 0.02535324]],

       [[0.13268065, 0.02865757, 0.13619695, 0.12050132],
        [0.04006628, 0.03476667, 0.15057998, 0.13929911],
        [0.12583083, 0.05162912, 0.0326132 , 0.13135502],
        [0.08635816, 0.15670481, 0.03819891, 0.03075794]],

       [[0.12446232, 0.0268825 , 0.12776082, 0.11303739],
        [0.03758455, 0.0326132 , 0.14125296, 0.13067083],
        [0.11803679, 0.04843117, 0.03059311, 0.1232188 ],
        [0.08100908, 0.14699841, 0.03583284, 0.02885277]],

       [[0.11738206, 0.02535324, 0.12049291, 0.10660705],
        [0.03544648, 0.03075794, 0.13321753, 0.12323738],
        [0.11132205, 0.04567608, 0.02885277, 0.11620928],
        [0.07640073, 0.13863614, 0.03379442, 0.02721143]]])