In [1]:
import numpy as np

In [2]:
a=np.arange(1000).reshape(-1,100)

In [20]:
a=a.flatten()

In [21]:
b=a.astype(int).ravel()

In [28]:
c=np.equal(a,b)
np.unique(c)


array([False])

In [29]:
def Sigmoid(X):
    return 1.0/(1.0+np.exp(X))

In [30]:
a=np.array([[0.1,0.2],[0.3,0.4],[0.5,0.6]])
b=np.array([[0.2,0.1],[0.2,0.3],[0.1,0.4]])
A1=np.dot(a,b.T)
print(A1)
H1=Sigmoid(A1)
print(H1)

[[0.04 0.08 0.09]
 [0.1  0.18 0.19]
 [0.16 0.28 0.29]]
[[0.49000133 0.48001066 0.47751518]
 [0.47502081 0.45512111 0.45264238]
 [0.46008512 0.43045378 0.42800387]]


In [43]:
c=np.array([0.3,0.1,0.4])
A2=np.dot(H1,c.T)
print(A2)
H2=Sigmoid(A2)
H2

[0.38600754 0.36907531 0.35227246]


array([0.40467877, 0.40876448, 0.41283146])

In [51]:
H2=H2.reshape(-1,1) if (H2.ndim==1) else H2
H2

array([[0.40467877],
       [0.40876448],
       [0.41283146]])

In [57]:
np.dot(H2.T,A1)

array([[0.12311663, 0.22154472, 0.23380747]])