In [2]:
import numpy as np

In [3]:
a=np.random.randint(1,10,(4,4))
a

array([[3, 6, 7, 3],
       [9, 1, 3, 6],
       [2, 9, 6, 6],
       [7, 1, 5, 8]])

In [5]:
np.exp(a)

array([[2.00855369e+01, 4.03428793e+02, 1.09663316e+03, 2.00855369e+01],
       [8.10308393e+03, 2.71828183e+00, 2.00855369e+01, 4.03428793e+02],
       [7.38905610e+00, 8.10308393e+03, 4.03428793e+02, 4.03428793e+02],
       [1.09663316e+03, 2.71828183e+00, 1.48413159e+02, 2.98095799e+03]])

In [7]:
1/(1+np.exp(a))

array([[4.74258732e-02, 2.47262316e-03, 9.11051194e-04, 4.74258732e-02],
       [1.23394576e-04, 2.68941421e-01, 4.74258732e-02, 2.47262316e-03],
       [1.19202922e-01, 1.23394576e-04, 2.47262316e-03, 2.47262316e-03],
       [9.11051194e-04, 2.68941421e-01, 6.69285092e-03, 3.35350130e-04]])