In [181]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as pl
from matplotlib.colors import ListedColormap
cmap=ListedColormap(['#FF0000','#00FF00','#0000FF'])
from collections import Counter

In [182]:
iris=datasets.load_iris()
X,y=iris.data,iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,
                    test_size=0.2,random_state=1234)

In [183]:
distance_original=[]
distance_argsort=[]
distancek=[]
common=[]
def euclidean_distance(x1,x2):
    a=np.sqrt(np.sum((x1-x2)**2))
    return a

class KNN:
    def __init__(self,k=3):
        self.k=k
        
    def fit(self,X,y):
        self.X_train=X
        self.y_train=y
        
    def predict(self,X):
        predicted_label=[self._predict(x) for x in X]
        return np.array(predicted_label)
    
    def _predict(self,x):
#         Compute Distances
        distances=[euclidean_distance(x,x_train) for x_train in self.X_train]
        distance_original.append(distances)
        
#         Get K nearest samples,labels
        k_indices=np.argsort(distances)[:self.k]
        k_nearest_labels=[self.y_train[i] for i in k_indices]
        distancek.append(k_nearest_labels)
        distance_argsort.append(k_indices)
        
#         Majority vote, most common class
        most_common=Counter(k_nearest_labels).most_common(1)
        common.append(most_common)
        return most_common[0][0]
    
    

In [184]:
clf=KNN(k=5)
clf.fit(X_train,y_train)
predictions=clf.predict(X_test[:1,:])

In [185]:
a=np.argsort(distance_original)
a[:5]

array([[ 47,  23,  65,  54,  41,  55,   1, 105,  28,  26,  64,  99,  77,
          3,  74,  59,  66,  62,  86,  93,  58,  70,  48, 103,  79,  50,
         60,   4,  11,  76,  73,  37,  87,  27,  33,  80, 104,  21,  43,
         32,  71,  75, 107, 116,  39,  38, 117,  25,  16,  91, 106,  17,
         52, 100,  89,  13,  53,  83,  84, 108, 112,  98,  63,  19,  92,
        109,  40, 115,  14,   9,  85,  24,   0,  31,  90,  18,  22,  45,
        110,  61, 114,  56,   7,   5,  49,  72, 111,  44,  82,  34, 113,
         30,  51,  95, 101,  81,  29,  46,  15,  36,  10,  57,  20,  69,
         68,  42,  97,  12,  35,   2,  94, 102, 119,  88,  96,   6,  67,
        118,   8,  78]], dtype=int64)

In [196]:
b=[]
for i in [47,  23,  65,  54,  41]:
    b.append(y_train[i])
b=np.array(b)
b,Counter(b).most_common()

(array([1, 1, 1, 2, 1]), [(1, 4), (2, 1)])

In [168]:
distance_argsort

[array([47, 23, 65, 54, 41], dtype=int64)]

In [169]:
common

[[(1, 4)]]

In [170]:
distancek

[[1, 1, 1, 2, 1]]

In [171]:
predictions

array([1])

In [172]:
acc=np.sum(predictions==y_test)/len(y_test)
acc

0.43333333333333335